### ISSUE TITLE
InitError: ccall: could not find function GAP_EvalString

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/GAP.jl#511] opened 2020-08-24 11:22 UTC
`HomalgProject.jl` fails with `Julia 1.3 - macOS-latest - x64` with the error

```
InitError: ccall: could not find function GAP_EvalString
```

https://github.com/homalg-project/HomalgProject.jl/runs/1021102739

As can be seen from the above link all other test combinations work.

**Comment by fingolfin** [comment] 2020-08-24 12:33
This is a duplicate of #509; if you have a way to reproduce this in a place where one can use the system interactively (i.e. not on Travis), that'd be super helpful

**Comment by mohamed-barakat** [comment] 2020-08-24 12:45
OK, thank you for the clarification. I looked at #509 but wasn't sure it is the same issue. I do not use Travis anymore and the issue only occurs on Mac OS, so I cannot reproduce it on the server. Is there any Mac OS machine on which you could give me remote access?

**Comment by fingolfin** [comment] 2020-09-04 12:19
Closing this as a duplicate

**Closed by fingolfin** 2020-09-04 12:19 UTC
