### ISSUE TITLE
side-effect of error traceback

### ISSUE THREAD

**Issue by ThomasBreuer** [oscar-system/GAP.jl#528] opened 2020-10-02 09:19 UTC
Pull request #520 is less harmless as it seemed to be.

Changing the value of `AlwaysPrintTracebackOnError` affects the behaviour of GAP's `Test`:
If errors occur in a GAP testfile then differences are reported because the output now looks differently.
As an example, try the following GAP input.
```
gap> AlwaysPrintTracebackOnError:= true;;
gap> Test( Filename( DirectoriesLibrary( "tst" ), "testinstall/zmodnz.tst" ) );
```
I think that this problem should be fixed on the GAP side, for example by setting `AlwaysPrintTracebackOnError` to `false` during tests.
(For the moment, we can "protect" the GAP testfiles in JuliaInterface by calling a modified `Test` function.)

*However*,
when GAP is running with Julia integration then the above GAP input causes Julia (1.4) to crash.
Can you reproduce this?
What is going on here?

(Besides that, should we perhaps reset `AlwaysPrintTracebackOnError` to `false` in GAP sessions, that is, when `GAP.prompt()` is called from Julia?)

**Comment by fingolfin** [comment] 2020-10-06 09:30
Yes I can reproduce the crash, and will look into that:
```
julia> GAP.prompt()
gap> AlwaysPrintTracebackOnError:= true;;
gap> Test( Filename( DirectoriesLibrary( "tst" ), "testinstall/zmodnz.tst" ) );
# line 18 of 530 (3%)
signal (11): Segmentation fault: 11
in expression starting at REPL[15]:1
FuncPRINT_CURRENT_STATEMENT at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
ExecProccall2args at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
ExecSeqStat6 at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
ExecWhile at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
ExecSeqStat7 at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
EXEC_CURR_FUNC at /Users/mhorn/.julia/packages/GAP/7w7Vl/deps/build/gap-4.11.0-julia-1.5/.libs/libgap.dylib (unknown line)
...
```

I think on the long run, what we want is perhaps to instead replace GAP's `ErrorInner` by a custom function of our own making, where we have full control over e.g. backtraces; and then perhaps not just print them, but somehow "integrate" them with the backtraces in Julia exceptions... ??! That's admittedly a rather fuzzy and imprecise crazy thought. This needs some more thought and discussion.

In the meantime, we can of course (ab)use `AlwaysPrintTracebackOnError` as we want. I agree that on the GAP side, it would be good if `Test` set `AlwaysPrintTracebackOnError:=false` (and restored it to the original value afterwards), and I see you have submitted https://github.com/gap-system/gap/pull/4124 doing that -- great.

**Comment by fingolfin** [comment] 2020-10-06 15:49
The crash occurs because `Obj func = FUNC_LVARS(context);` inside `PRINT_CURRENT_STATEMENT` produces a NULL pointer. I have not yet investigated why that is.

**Comment by fingolfin** [comment] 2021-07-27 13:33
One part of this was fixed by Thomas via https://github.com/gap-system/gap/pull/4124 ; the crash was also gone, it is currently back, but PR #674 fixes it again.

**Closed** 2021-07-27 13:33 UTC
Labels: kind: bug
